apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-api
  labels:
    app: fake-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: fake-api
    spec:
      containers:
        - name: fake-api
          image: johnwesonga/fake-api:{{ .Release }}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 9000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fake-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app: fake-api
spec:
  rules:
    - host: fake-api.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fake-api
                port:
                  number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: fake-api
  labels:
    app: fake-api
spec:
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http
  selector:
    app: fake-api

---
