apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-api
  labels:
    app: fake-api
spec:
  replicas: 3
  selector:
    matchLabels:
        app: fake-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: fake-api
    spec:
      containers:
      - name: fake-api
        image: docker.io/johnwesonga/fake-api:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        resources:
          limits:
            cpu: 10m
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 30Mi
      terminationGracePeriodSeconds: 30